import type { NextPage } from 'next'
import Head from 'next/head'
import Sidebar from '../components/Sidebar'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Whatsapp 4.0</title>
        <meta name="description" content="Generated by Lamdaik" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href='/whatsapp-icon.png' />
        
      </Head>
      <Sidebar/>
    </div>
  )
}

export default Home
